# Generated by Django 4.0.5 on 2022-08-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
